version: '3.8'

services:
  mlflow:
    image: python:3.11-slim
    container_name: mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./models:/models
    working_dir: /app
    command: >
      bash -c "
      pip install mlflow[extras]==2.10.2 &&
      mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlruns --default-artifact-root file:///models
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  classifier:
    build:
      context: .
      dockerfile: Dockerfile.classifier
    container_name: classifier
    ports:
      - "8001:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./models:/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  llm:
    image: ghcr.io/ggerganov/llama.cpp:server
    container_name: llm
    ports:
      - "11434:11434"
    volumes:
      - ./models:/models
    command: >
      --host 0.0.0.0 --port 11434 
      --model /models/qwen2.5-0.5b-instruct-q4_k_m.gguf
      --ctx-size 2048
      --threads 4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    container_name: orchestrator
    ports:
      - "8000:8000"
    depends_on:
      - classifier
      - llm
    environment:
      - CLASSIFIER_URL=http://classifier:8000
      - LLM_URL=http://llm:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: web
    ports:
      - "8501:8501"
    depends_on:
      - orchestrator
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 30s
      timeout: 10s
      retries: 3