app = "youarebot-orchestrator"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile.orchestrator"

[env]
  PORT = "8000"

[http_services]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_services.machine]]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 512

[machines]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512