app = "supakavadee-r-harbour-ml-solution"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  USE_MEMORY_DB = "true"
  MODEL_PATH = "/models/bot_classifier"

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2